services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    volumes:
      - redis_data:/data

  web:
      build: .
      command: bash -c "python manage.py wait_for_database &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - mysql

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
